{% set name = "empyre" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/empyre-{{ version }}.tar.gz
  sha256: 006317355dc65d7bc4760a5e661564bad6aacdc792a6ccce3af3173488f18fe9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.2
    - numpy >=1.17
    - pillow
    - scikit-image
    - scipy
    - tqdm

test:
  imports:
    - empyre
  commands:
    - pip check
    - pytest tests
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest
    - pytest-cov
    - pytest-flake8
    - pytest-runner
    - python {{ python_min }}

about:
  home: https://iffgit.fz-juelich.de/empyre/empyre
  summary: Electron Microscopy Python Reconstruction
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://empyre.iffgit.fz-juelich.de/empyre/
  dev_url: https://iffgit.fz-juelich.de/empyre/empyre

extra:
  recipe-maintainers:
    - jan-car
    - sk1p
    - uellue
    - matbryan52
